# Generated by Django 3.0.4 on 2020-04-05 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_favorited'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
