# Generated by Django 3.0.4 on 2020-04-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_website', '0015_remove_product_favorited'),
        ('users', '0007_auto_20200405_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favorited',
            field=models.ManyToManyField(blank=True, related_name='users', to='sub_website.Product'),
        ),
    ]
