# Generated by Django 3.0.4 on 2020-04-06 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200405_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='favorited',
            new_name='favorites',
        ),
    ]
