# Generated by Django 3.0.4 on 2020-10-20 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20201020_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nom',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='prenom',
            field=models.CharField(default='', max_length=255),
        ),
    ]
