language: python
job:
  include:
        env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
              env: PATH=functional_tests\chromedriver.exe

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
before_script:
- python manage.py migrate
script:
  - python manage.py test