dist: bionic
language: python

python:
  - '3.7'

addons:
  # ajouter uniquement les navigateurs utilisés
  chrome: stable
  firefox: latest

install:
  pip install -r requirements.txt

before_script:
  - python manage.py migrate

env:
  global:
    - DJANGO_SETTINGS_MODULE="config.settings.travis"

services:
  - postgresql

script:
  - python manage.py test 