  
dist: bionic
language: python

python:
  - '3.6'

addons:
  # ajouter uniquement les navigateurs utilisés
  chrome: stable
  firefox: latest

branches:
  only:
    - staging
install:
  pip install-r requirements.txt

before_script:
  # ajouter tchappui-webdrivers dans requirements.txt
  - install-webdrivers
  - python manage.py migrate

env:
  global:
    - DJANGO_SETTINGS_MODULE="config.settings.travis"

services:
  - postgresql

script:
  - python manage.py test 