dist: bionic
language: python
job:
  include:
        env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
# command to install dependencies
addons:
  # ajouter uniquement les navigateurs utilisés
  chrome: stable
  firefox: latest

services:
  -postgresql
before_script:
  - psql -c "CREATE DATABASE travisci;" -U postgres
  - install -webdrivers
  - python manage.py migrate

before_install:
  - export DJANGO_SETTINGS_MODULE=sub_project.settings
  - export PYTHONPATH=$HOME/builds/Bayard75/Projet8-Plateforme-de-substitution
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
  - pip install psycopg2 --quiet
# command to run tests
before_script:
- python manage.py migrate
script:
  - python manage.py test

