language: python
job:
  include:
        env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
# command to install dependencies
addons:
  # ajouter uniquement les navigateurs utilisés
  chrome: stable
  firefox: latest

services:
  -postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
install:
  - pip install -r requirements.txt
# command to run tests
before_script:
- python manage.py migrate
script:
  - python manage.py test