version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Install python dependancies
          command: |
            pip install --user -r requirements.txt
      - run:
          name: Settings Environnement variables
          command: |
            echo 'export DEBUG_ENV_VARIABLE="True"'
            echo 'export SUB_PROJECT_SK="3bed2b4a461e5f699fa66392a870c0e5e566004ec4e2f4b6"'
      - run:
          name: Migration database
          command: |
            python manage.py migrate
      - run:
          name: Populating Database
          command: |
            python manage.py populate_database
      - run:
          name: Testing app
          command: |
            python manage.py test

workflows:
  main:
    jobs:
      - build-and-test
