# Generated by Django 3.0.4 on 2020-03-29 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('codebar', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('categories', models.TextField()),
                ('grade', models.CharField(max_length=1)),
                ('url', models.URLField()),
                ('reperes', models.URLField()),
                ('image', models.URLField()),
            ],
        ),
    ]
