# Generated by Django 3.0.4 on 2020-03-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_website', '0002_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
        migrations.AddField(
            model_name='product',
            name='Category',
            field=models.ManyToManyField(related_name='categories', to='sub_website.Category'),
        ),
    ]
