# Generated by Django 3.0.4 on 2020-03-31 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_website', '0005_auto_20200331_0029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('toppings', models.ManyToManyField(related_name='pizzas', to='sub_website.Topping')),
            ],
        ),
    ]
