# Generated by Django 3.0.4 on 2020-03-31 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_website', '0006_pizza_topping'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pizza',
        ),
        migrations.DeleteModel(
            name='Topping',
        ),
    ]
