# Generated by Django 3.0.4 on 2020-03-31 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_website', '0007_auto_20200331_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Category',
        ),
    ]
