# Generated by Django 3.0.4 on 2020-03-31 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_website', '0008_remove_product_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
