# Generated by Django 3.0.4 on 2020-03-31 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_website', '0010_category_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
