# Generated by Django 3.0.4 on 2020-04-01 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sub_website', '0011_auto_20200331_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_cat',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sub_website.Category'),
        ),
    ]
