# Generated by Django 3.0.4 on 2020-04-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('sub_website', '0013_auto_20200401_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='favorited',
            field=models.ManyToManyField(related_name='favorites', to='users.Profile'),
        ),
    ]
