# Generated by Django 3.0.4 on 2020-04-05 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_website', '0014_product_favorited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='favorited',
        ),
    ]
