# Generated by Django 3.0.4 on 2020-04-18 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_website', '0015_remove_product_favorited'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fallback_cat',
            field=models.CharField(default=None, max_length=256),
            preserve_default=False,
        ),
    ]
