# Generated by Django 3.0.4 on 2020-04-18 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_website', '0016_product_fallback_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fallback_cat',
            field=models.CharField(default='None', max_length=256),
        ),
    ]
