# Generated by Django 3.0.4 on 2020-11-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_website', '0017_auto_20200418_0346'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stores',
            field=models.CharField(default='[]', max_length=256),
        ),
    ]
