# Generated by Django 3.0.4 on 2020-12-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_website', '0018_product_stores'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='favorited',
            field=models.IntegerField(default=0, max_length=256),
        ),
    ]
